import type { Preset } from "./tipos";

/** Planilla de propiedades de una inmobiliaria.
 *
 *  La suciedad NO es inventada al azar: son las cuatro formas en que un
 *  argentino carga un teléfono, la localidad escrita de tres maneras, el
 *  CUIT que Excel convirtió a notación científica solo, y la misma
 *  propiedad cargada dos veces por dos personas distintas. Si el dueño no
 *  reconoce su propia planilla acá, la muestra no sirve.
 *
 *  Negocios, personas y direcciones son ficticios. Los teléfonos siguen un
 *  patrón fijo (4047-00XX) para que no sean ruteables. */

const LOCALIDADES = [
  { valor: "Martínez", alias: [] },
  { valor: "San Isidro", alias: ["s. isidro", "s isidro"] },
  { valor: "Vicente López", alias: ["vte. lópez", "vte lopez", "v. lopez"] },
  { valor: "Olivos", alias: [] },
  { valor: "Boulogne", alias: [] },
  { valor: "Beccar", alias: [] },
  { valor: "Acassuso", alias: [] },
  { valor: "Florida", alias: [] },
];

export const propiedades: Preset = {
  slug: "propiedades",
  nombre: "Planilla de propiedades",
  rubro: "Inmobiliaria",
  gancho:
    "Cuatro formas de escribir el mismo teléfono, la localidad en tres grafías y dos propiedades cargadas dos veces.",
  columnas: [
    { clave: "direccion", titulo: "Dirección", tipo: "texto" },
    { clave: "localidad", titulo: "Localidad", tipo: "localidad", canonicos: LOCALIDADES },
    { clave: "tipo", titulo: "Tipo", tipo: "texto" },
    { clave: "precio", titulo: "Precio", tipo: "moneda" },
    { clave: "propietario", titulo: "Propietario", tipo: "nombre", clavePara: "dedupe" },
    { clave: "telefono", titulo: "Teléfono", tipo: "telefono" },
    { clave: "cuit", titulo: "CUIT", tipo: "cuit" },
    { clave: "publicado", titulo: "Publicado", tipo: "fecha" },
  ],
  filas: [
    {
      direccion: "Av. Maipú 2847",
      localidad: "Martínez",
      tipo: "Depto 2 amb",
      precio: "U$S 185.000",
      propietario: "Silvia Ferrer",
      telefono: "11 4047-0012",
      cuit: "20-12345678-6",
      publicado: "12/3/26",
    },
    {
      direccion: "av. maipu 2847",
      localidad: "MARTINEZ",
      tipo: "depto 2 ambientes",
      precio: "185000",
      propietario: "silvia ferrer",
      telefono: "+54 9 11 4047 0012",
      cuit: "",
      publicado: "2026-03-12",
    },
    {
      direccion: "Paraná 1290",
      localidad: "Vte. López",
      tipo: "Casa 3 amb",
      precio: "U$S 320.000",
      propietario: "Ricardo Paz",
      telefono: "1140470034",
      cuit: "27-23456789-1",
      publicado: "5/2/26",
    },
    {
      direccion: "Ader 455",
      localidad: "VICENTE LOPEZ",
      tipo: "PH 3 amb",
      precio: "$ 145.000.000",
      propietario: "MARTA GONZALEZ",
      telefono: "4047-0056",
      cuit: "30-71234567-8",
      publicado: "18/02/2026",
    },
    {
      direccion: "Av. del Libertador 15200",
      localidad: "San Isidro",
      tipo: "Depto 4 amb",
      precio: "U$S 450.000",
      propietario: "Jorge Beltrán",
      telefono: "11 4047-0078",
      cuit: "3.07123E+10",
      publicado: "2026-01-30",
    },
    {
      direccion: "Roca 812",
      localidad: "BOULOGNE",
      tipo: "Casa 4 amb",
      precio: "U$S 210.000",
      propietario: "Nora Quiroga",
      telefono: "",
      cuit: "23-34567890-5",
      publicado: "22/1/26",
    },
    {
      direccion: "25 de Mayo 340",
      localidad: "Olivos",
      tipo: "Local comercial",
      precio: "$ 98.500.000",
      propietario: "Hugo Sarmiento",
      telefono: "11 4047-0090",
      cuit: "20-28765432-5",
      publicado: "3/3/26",
    },
    {
      direccion: "Diag. Salta 77",
      localidad: "vte lopez",
      tipo: "Depto 1 amb",
      precio: "U$S 92.000",
      propietario: "Ana Lucero",
      telefono: "549 11 4047 0111",
      cuit: "20-35421876-4",
      publicado: "2026-02-14",
    },
    {
      direccion: "paraná 1290",
      localidad: "Vicente López",
      tipo: "casa 3 ambientes",
      precio: "U$S 320.000",
      propietario: "RICARDO PAZ",
      telefono: "11 4047-0034",
      cuit: "",
      publicado: "5/2/2026",
    },
    {
      direccion: "Ader 455",
      localidad: "Vicente Lopez",
      tipo: "ph 3 amb",
      precio: "",
      propietario: "Marta González",
      telefono: "11 4047-0056",
      cuit: "",
      publicado: "",
    },
    {
      direccion: "Alvear 620",
      localidad: "Beccar",
      tipo: "Casa 5 amb",
      precio: "U$S 680.000",
      propietario: "Elena Ferraro",
      telefono: "11 4047-0123",
      cuit: "27-12908734-5",
      publicado: "11/3/26",
    },
    {
      direccion: "Av. Maipú 3100",
      localidad: "martinez",
      tipo: "Depto 3 amb",
      precio: "U$S 240.000",
      propietario: "Pablo Iriarte",
      telefono: "11 4047-0145",
      cuit: "",
      publicado: "28/2/26",
    },
    {
      direccion: "Carlos Tejedor 190",
      localidad: "Florida",
      tipo: "PH 2 amb",
      precio: "$ 76.000.000",
      propietario: "Diego Ocampo",
      telefono: "11 4047-0167",
      cuit: "",
      publicado: "2026-03-01",
    },
    {
      direccion: "Av. del Libertador 14050",
      localidad: "ACASSUSO",
      tipo: "Casa 6 amb",
      precio: "U$S 950.000",
      propietario: "Cecilia Maldonado",
      telefono: "11 4047-0189",
      cuit: "",
      publicado: "7/3/26",
    },
    {
      direccion: "Roca 812",
      localidad: "Boulogne",
      tipo: "casa 4 ambientes",
      precio: "U$S 210.000",
      propietario: "nora quiroga",
      telefono: "11 4047-0201",
      cuit: "",
      publicado: "22/01/2026",
    },
  ],
};
